[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ;https://github.com/me-no-dev/ESPAsyncWebServer.git
    ;https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/mathieucarbou/ESPAsyncWebServer#v3.3.23
    https://github.com/mathieucarbou/AsyncTCP#v3.2.0
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    milesburton/DallasTemperature @ ^3.9.1
    paulstoffregen/OneWire @ ^2.3.8
    adafruit/Adafruit AHTX0 @ ^2.0.5 
    mikalhart/TinyGPSPlus @ ^1.0.3
    robtillaart/PCF8574@^0.3.7

board_build.filesystem = littlefs

# Résolution des dépendances et inclusion des headers du dossier include/ :
lib_ldf_mode = deep+
build_flags = -I include ;-D DEBUG_ENABLED ;Pour désactiver le debug en production : commenter -D DEBUG_ENABLED et recompiler.